unstable_features = true

format_code_in_doc_comments = true
format_strings = true
imports_granularity = "Crate"
imports_layout = "HorizontalVertical"
normalize_comments = true
reorder_impl_items = true
use_field_init_shorthand = true
wrap_comments = true
